import type { SmallEvent } from './types';

export const gecEvents: SmallEvent[] = [
  {
    id: 'gec-ai-ml-workshop-2026',
    institutionId: 'gec-gaya',
    title: 'Hands-on AI & Machine Learning Workshop',
    shortDescription: 'Practical deep learning, prompt engineering, and neural network fundamentals.',
    description: `An intensive hands-on workshop led by industry practitioners covering machine learning workflows, Python data science libraries (PyTorch, Pandas, Scikit-Learn), and modern generative AI models.

Participants will build and deploy a working computer vision model by the end of the session. E-Certificates will be distributed to verified attendees.`,
    date: '2026-10-12',
    startTime: '09:30',
    endTime: '16:30',
    venue: 'Auditorium Hall, GEC Gaya',
    banner: '/icon-512.png',
    organizer: 'Department of Computer Science & Engineering, GEC Gaya',
    category: 'Workshop',
    registrationEnabled: true,
    registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfp9g8h7i6j5k4l3m2n1o0p9q8r7s6t5u4v/viewform',
    registrationLabel: 'Register Now',
    status: 'UPCOMING',
    createdAt: '2026-10-01T14:00:00Z',
    registrationDeadline: '2026-10-11T20:00:00Z',
  },
  {
    id: 'gec-tech-symposium-2026',
    institutionId: 'gec-gaya',
    title: 'State-Level Technical Project Symposium 2026',
    shortDescription: 'Display your final-year and pre-final year hardware & software innovations.',
    description: `A state engineering symposium bringing together student engineers to showcase working IoT prototypes, robotics projects, web platforms, and civil engineering designs.

Judged by senior academic faculty and tech entrepreneurs. Cash awards for Top 3 innovations across departments.`,
    date: '2026-10-18',
    startTime: '10:00',
    endTime: '17:00',
    venue: 'Main Seminar Hall, Academic Block, GEC Gaya',
    banner: '/icon-512.png',
    organizer: 'Technical Innovation Cell & IIC, GEC Gaya',
    category: 'Technical',
    registrationEnabled: true,
    registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd1e2f3g4h5i6j7k8l9m0n1o2p3q4r5s6t7u/viewform',
    registrationLabel: 'Register Project Entry',
    status: 'UPCOMING',
    createdAt: '2026-10-02T16:00:00Z',
    registrationDeadline: '2026-10-16T23:59:59Z',
  },
  {
    id: 'gec-cloud-devops-seminar-2026',
    institutionId: 'gec-gaya',
    title: 'Modern Cloud Architecture & DevOps Seminar',
    shortDescription: 'Master Docker, Kubernetes, CI/CD pipelines, and cloud-native scaling.',
    description: `Special guest lecture and career interactive session exploring real-world cloud architectures, microservices, containerization with Docker and Kubernetes, and automated deployment pipelines.`,
    date: '2026-10-25',
    startTime: '14:00',
    endTime: '17:30',
    venue: 'Smart Classroom 201, GEC Gaya',
    banner: '/icon-512.png',
    organizer: 'GEC Tech Club',
    category: 'Seminar',
    registrationEnabled: true,
    registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t/viewform',
    registrationLabel: 'Register for Seminar',
    status: 'UPCOMING',
    createdAt: '2026-10-03T11:00:00Z',
    registrationDeadline: '2026-10-24T18:00:00Z',
  },
];
